### ISSUE TITLE
Import error

### ISSUE THREAD

**Issue by akashcas** [ncsuarc/generate_targets#1]
```
python generate.py --number 10 --size 50 --blur 1
Traceback (most recent call last):
  File "generate.py", line 5, in <module>
    import Target
  File "/home/akash/generate_targets/Target.py", line 1, in <module>
    from enum import Enum, unique
ImportError: cannot import name unique
```

**Comment by Perseus101** [comment]
What version of python are you using?

**Comment by akashcas** [comment]
Python 2.7

**Comment by Perseus101** [comment]
The enum module works fine for me on Python 2.7.13
Try running this:
python -c "from enum import Enum, unique"
If you get the same error, then there is some sort of issue with your version of Python.

You can also try running the code with Python 3.
